### ISSUE TITLE
message IDs bigger then int32

### ISSUE THREAD

**Issue by kit230986** [andersmandersen/gatewayapi-dotnet#1]
GatewayAPI.Responses.Result Ids can't be type List<int> because message IDs get bigger then int32 last message ID i have seen is 2147998031.
See [https://docs.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=net-6.0](https://docs.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=net-6.0) which give problem with GatewayAPI.GatewayAPIHandler.SendMessage that will throw an Exception.

**Comment by andersmandersen** [comment]
@kit230986 - A new package has been build and publish to Nuget. It should be available for update within a few hours. Keep a eye on the package page, when ready. https://www.nuget.org/packages/GatewayAPI/

Let me know if you have any further issues :)

**Comment by kit230986** [comment]
@andersmandersen - the method public CancelResult CancelScheduledMessage(int messageId) should also be changed to public CancelResult CancelScheduledMessage(long messageId). Method in GatewayAPI.GatewayAPIHandler.
